apiVersion: v1
kind: Secret
metadata:
  name: rarible-secret
type: Opaque
data:
  RARIBLE_API_KEY: <base64-encoded-placeholder>
  LOG_LEVEL: <base64-encoded-placeholder>
  HTTP_SERVER_PORT: <base64-encoded-placeholder>
