namespace: default
app: 
  name: rarible-app
  labels:
    tier: backend
replicaCount: 2
image:
  repository: megidy/rarible
  tag: latest
resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "1"
    memory: "1Gi"
service:
  type: NodePort
  port: 8080
container:
  port: 8080

