apiVersion: apps/v1
kind: Deployment
metadata:
  name: rarible-deployment
  namespace: default
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      tier: {{ .Values.app.labels.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        tier: backend
    spec:
      containers:
      - name: container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.container.port }}
        envFrom:
        - secretRef:
            name: rarible-secret
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
      