apiVersion: v1
kind: Service
metadata:
  name: rarible-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    app: rarible-app
    tier: backend
  type: {{ .Values.service.type }}