name: Build and test

on:
    push:
        branches: ["master"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup go
              uses:
                actions/setup-go@v5
              with:
                go-version: 1.24
            - name: build
              run: go build ./...
            - name: Run test
              run: go test -v -cover ./...
            
